### ISSUE TITLE
Serve sealed-secrets-web with path based ingress

### ISSUE THREAD

**Issue by dorroddorrod** [ricoberger/sealed-secrets-web#11]
Hi,
I'm trying to implement this web-ui on my EKS cluster and expose it through Ingress.
I'm using Nginx ingress and working with path based routing (e.g example.com/sealed-secrets)

This is how my ingress object looks like:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
  name: sealed-secrets-web
  namespace: kube-system
spec:
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              serviceName: sealed-secrets-web
              servicePort: http
            path: /sealed-secrets/?(.*)
```

When i try to render the web, the static content path is missing the `/sealed-secrets` and cannot be found so i'm getting 404.

![Screen Shot 2021-04-24 at 10 12 57](https://user-images.githubusercontent.com/31075689/115950774-e4eaef00-a4e5-11eb-8c7b-0abd7d576be8.png)

Any idea how can i make it work with path based routing?
