### ISSUE TITLE
new secret syntax format

### ISSUE THREAD

**Issue by solune** [ricoberger/sealed-secrets-web#9]
Hi,
Does the starting secret have to be in json format?
When I make a secret in yaml like this, I can't encode it : invalid character 'a' looking for beginning of value
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: admin
  password: toto
```
regards

**Comment by ricoberger** [comment]
Hi, you have to start Sealed Secrets Web with the `--format=yaml` flag and you have to pass the same formate to kubeseal `--kubeseal-arguments=--format yaml`. When you want to use yaml format you have to use the following values in the Helm chart:

```yaml
image:
  args:
    - --format=yaml
    - --kubeseal-arguments=--format yaml
```
